### ISSUE TITLE
Unnecessary dependency on Perl

### ISSUE THREAD

**Issue by me-and** [me-and/Cygwin-Git#31]
Per @svnpenn's comment at #26, can we also remove the base requirement on Perl? Need to investigate what actually requires it first.

**Comment by me-and** [comment]
https://cygwin.com/ml/cygwin/2017-07/msg00228.html:

> Currently only these files rely on it:
>
> * `usr/libexec/git-core/git-add--interactive`
> * `usr/libexec/git-core/git-archimport`

**Comment by me-and** [comment]
Closing per https://cygwin.com/ml/cygwin/2017-07/msg00288.html

Specifically, while `git add --interactive` and friends depend on Perl, splitting them off into a separate package is going to cause too much confusion. If and when those commands no longer depend on Perl, we can look at resurrecting this ticket.

**Comment by svnpenn** [comment]
I am putting this here so I can check periodically if they have ported to C - thanks

http://github.com/git/git/blob/master/git-add--interactive.perl
