### ISSUE TITLE
version discrepancy

### ISSUE THREAD

**Issue by svnpenn** [me-and/Cygwin-Git#39]
i see 2.16.2 here:

https://github.com/me-and/Cygwin-Git/blob/ddbc34b895ae47188f7efd9f7ce623682377e928/git.cygport#L11

but i see 2.17.0 here:

http://cygwin.com/ml/cygwin/2018-04/msg00126.html

**Comment by me-and** [comment]
Fixed. Commit was in the `next` branch, but it looks like I'd forgotten to move `master` forward when I published the release.
