### ISSUE TITLE
Update to recent Git version

### ISSUE THREAD

**Issue by E3V3A** [me-and/Cygwin-Git#40]
Are you the maintainer of the Cygwin `git` package?

If so please consider updating the 2014 based package to the latest git!

Apparently there are many fixes since on how windows console programs manage to mangle paths used in git, and thus kills certain apps from running. Such as using `go get`. 

Please see:
* https://github.com/golang/go/issues/23155
* https://github.com/git/git/commits/master?before=b5101f929789889c2e536d915698f58d5c5c6b7a+35&path%5B%5D=compat&path%5B%5D=mingw.c
* https://github.com/git/git/commit/1cadad6f658bfb3ab54b25dd04bac372253473b6#diff-a0c7aa297d8da1149ce761c31dc59328
* https://github.com/golang/go/issues/23155
* https://github.com/wtfutil/wtf/issues/350

**Comment by me-and** [comment]
I'm the Cygwin Git maintainer, yes. I've had trouble with apparent [BLODA](https://cygwin.com/acronyms/#BLODA) – Windows software that interferes with the Cygwin execution chain – that has been causing intermittent failures in the test suite; I'm reluctant to release something through the Cygwin official release channels that doesn't pass the Git test suite, but I've not had the bandwidth to investigate the failures for some time.

Nonetheless it's been a while since I've taken a look at this, and the underlying Cygwin interfaces have updated recently, so I'll check to see if things are in a better state again now.

**Comment by me-and** [comment]
In the interim, it's reasonably straightforward to compile Git in Cygwin yourself, if you want something that has recent features/fixes/&c. Obviously that's more work, and it doesn't get you something that's blessed as official and fully supported by the Cygwin project/community, but it may resolve your immediate problem.

**Comment by E3V3A** [comment]
@me-and

Yeah, I was at first looking at the windows related readme files and patches used in the original Cygwin package. But then I figured all those are outdated, and probably not maintained so I just dropped the idea of doing it myself, in hope someone who knew what they were doing would eventually get around to it. 

And if ever, that time should be soon, as git has seemingly changed somewhat and improved quite a bit. 

Didn't know about BLODA! :rofl:  People still use anti-virus!!?? Crazy!

But if you think it's easy to do, please let me know the steps.

**Comment by me-and** [comment]
For building and installing Git yourself, you should just be able to take the upstream Git repository (e.g. from https://github.com/git/git) and follow the instructions at the top of the `INSTALL` file.

**Comment by cup** [comment]
@E3V3A as i mentioned in the other issue - your Go issue can be fixed by upgrading to 
Cygwin Git 2.21.0. Ideally Adam would do this, but sadly he has let this important package fall out of regular development

so for the time being you will need to build yourself.

**Comment by zmajeed** [comment]
This repo does not have the latest release of cygwin git 2.21 from April 2019

https://cygwin.com/pipermail/cygwin/2018-April/236779.html

I hope it gets synced soon with the next release

https://cygwin.com/pipermail/cygwin/2020-January/243558.html

**Comment by me-and** [comment]
I'm working on updating the Git release. But I'm gonna close this ticket, as it's not tracking a bug or specific development work, and I don't want to use issues to track the core maintenance work.
